angular.module('IMDB.services',[])



.service('IO2_to_IO3',function(){
	var map={
    "AF": "AFG",
    "AX": "ALA",
    "AL": "ALB",
    "DZ": "DZA",
    "AS": "ASM",
    "AD": "AND",
    "AO": "AGO",
    "AI": "AIA",
    "AQ": "ATA",
    "AG": "ATG",
    "AR": "ARG",
    "AM": "ARM",
    "AW": "ABW",
    "AU": "AUS",
    "AT": "AUT",
    "AZ": "AZE",
    "BS": "BHS",
    "BH": "BHR",
    "BD": "BGD",
    "BB": "BRB",
    "BY": "BLR",
    "BE": "BEL",
    "BZ": "BLZ",
    "BJ": "BEN",
    "BM": "BMU",
    "BT": "BTN",
    "BO": "BOL",
    "BQ": "BES",
    "BA": "BIH",
    "BW": "BWA",
    "BV": "BVT",
    "BR": "BRA",
    "IO": "IOT",
    "BN": "BRN",
    "BG": "BGR",
    "BF": "BFA",
    "BI": "BDI",
    "CV": "CPV",
    "KH": "KHM",
    "CM": "CMR",
    "CA": "CAN",
    "KY": "CYM",
    "CF": "CAF",
    "TD": "TCD",
    "CL": "CHL",
    "CN": "CHN",
    "CX": "CXR",
    "CC": "CCK",
    "CO": "COL",
    "KM": "COM",
    "CG": "COG",
    "CD": "COD",
    "CK": "COK",
    "CR": "CRI",
    "CI": "CIV",
    "HR": "HRV",
    "CU": "CUB",
    "CW": "CUW",
    "CY": "CYP",
    "CZ": "CZE",
    "DK": "DNK",
    "DJ": "DJI",
    "DM": "DMA",
    "DO": "DOM",
    "EC": "ECU",
    "EG": "EGY",
    "SV": "SLV",
    "GQ": "GNQ",
    "ER": "ERI",
    "EE": "EST",
    "ET": "ETH",
    "FK": "FLK",
    "FO": "FRO",
    "FJ": "FJI",
    "FI": "FIN",
    "FR": "FRA",
    "GF": "GUF",
    "PF": "PYF",
    "TF": "ATF",
    "GA": "GAB",
    "GM": "GMB",
    "GE": "GEO",
    "DE": "DEU",
    "GH": "GHA",
    "GI": "GIB",
    "GR": "GRC",
    "GL": "GRL",
    "GD": "GRD",
    "GP": "GLP",
    "GU": "GUM",
    "GT": "GTM",
    "GG": "GGY",
    "GN": "GIN",
    "GW": "GNB",
    "GY": "GUY",
    "HT": "HTI",
    "HM": "HMD",
    "VA": "VAT",
    "HN": "HND",
    "HK": "HKG",
    "HU": "HUN",
    "IS": "ISL",
    "IN": "IND",
    "ID": "IDN",
    "IR": "IRN",
    "IQ": "IRQ",
    "IE": "IRL",
    "IM": "IMN",
    "IL": "ISR",
    "IT": "ITA",
    "JM": "JAM",
    "JP": "JPN",
    "JE": "JEY",
    "JO": "JOR",
    "KZ": "KAZ",
    "KE": "KEN",
    "KI": "KIR",
    "KP": "PRK",
    "KR": "KOR",
    "KW": "KWT",
    "KG": "KGZ",
    "LA": "LAO",
    "LV": "LVA",
    "LB": "LBN",
    "LS": "LSO",
    "LR": "LBR",
    "LY": "LBY",
    "LI": "LIE",
    "LT": "LTU",
    "LU": "LUX",
    "MO": "MAC",
    "MK": "MKD",
    "MG": "MDG",
    "MW": "MWI",
    "MY": "MYS",
    "MV": "MDV",
    "ML": "MLI",
    "MT": "MLT",
    "MH": "MHL",
    "MQ": "MTQ",
    "MR": "MRT",
    "MU": "MUS",
    "YT": "MYT",
    "MX": "MEX",
    "FM": "FSM",
    "MD": "MDA",
    "MC": "MCO",
    "MN": "MNG",
    "ME": "MNE",
    "MS": "MSR",
    "MA": "MAR",
    "MZ": "MOZ",
    "MM": "MMR",
    "NA": "NAM",
    "NR": "NRU",
    "NP": "NPL",
    "NL": "NLD",
    "NC": "NCL",
    "NZ": "NZL",
    "NI": "NIC",
    "NE": "NER",
    "NG": "NGA",
    "NU": "NIU",
    "NF": "NFK",
    "MP": "MNP",
    "NO": "NOR",
    "OM": "OMN",
    "PK": "PAK",
    "PW": "PLW",
    "PS": "PSE",
    "PA": "PAN",
    "PG": "PNG",
    "PY": "PRY",
    "PE": "PER",
    "PH": "PHL",
    "PN": "PCN",
    "PL": "POL",
    "PT": "PRT",
    "PR": "PRI",
    "QA": "QAT",
    "RE": "REU",
    "RO": "ROU",
    "RU": "RUS",
    "RW": "RWA",
    "BL": "BLM",
    "SH": "SHN",
    "KN": "KNA",
    "LC": "LCA",
    "MF": "MAF",
    "PM": "SPM",
    "VC": "VCT",
    "WS": "WSM",
    "SM": "SMR",
    "ST": "STP",
    "SA": "SAU",
    "SN": "SEN",
    "RS": "SRB",
    "SC": "SYC",
    "SL": "SLE",
    "SG": "SGP",
    "SX": "SXM",
    "SK": "SVK",
    "SI": "SVN",
    "SB": "SLB",
    "SO": "SOM",
    "ZA": "ZAF",
    "GS": "SGS",
    "SS": "SSD",
    "ES": "ESP",
    "LK": "LKA",
    "SD": "SDN",
    "SR": "SUR",
    "SJ": "SJM",
    "SZ": "SWZ",
    "SE": "SWE",
    "CH": "CHE",
    "SY": "SYR",
    "TW": "TWN",
    "TJ": "TJK",
    "TZ": "TZA",
    "TH": "THA",
    "TL": "TLS",
    "TG": "TGO",
    "TK": "TKL",
    "TO": "TON",
    "TT": "TTO",
    "TN": "TUN",
    "TR": "TUR",
    "TM": "TKM",
    "TC": "TCA",
    "TV": "TUV",
    "UG": "UGA",
    "UA": "UKR",
    "AE": "ARE",
    "GB": "GBR",
    "US": "USA",
    "UM": "UMI",
    "UY": "URY",
    "UZ": "UZB",
    "VU": "VUT",
    "VE": "VEN",
    "VN": "VNM",
    "VG": "VGB",
    "VI": "VIR",
    "WF": "WLF",
    "EH": "ESH",
    "YE": "YEM",
    "ZM": "ZMB",
    "ZW": "ZWE"
  };
  return function (countryCode_2) {
    if (map.hasOwnProperty(countryCode_2)) {
        return map[countryCode_2];
    } else {
        return countryCode_2;
    }
  }

})

.service('CountryIso',function(){
    var isoCountries1 = [
{'ccode' : 'AF', 'cname' : 'Afghanistan'},
{'ccode' : 'AX', 'cname' : 'Aland Islands'},
{'ccode' : 'AL', 'cname' : 'Albania'},
{'ccode' : 'DZ', 'cname' : 'Algeria'},
{'ccode' : 'AS', 'cname' : 'American Samoa'},
{'ccode' : 'AD', 'cname' : 'Andorra'},
{'ccode' : 'AO', 'cname' : 'Angola'},
{'ccode' : 'AI', 'cname' : 'Anguilla'},
{'ccode' : 'AQ', 'cname' : 'Antarctica'},
{'ccode' : 'AG', 'cname' : 'Antigua And Barbuda'},
{'ccode' : 'AR', 'cname' : 'Argentina'},
{'ccode' : 'AM', 'cname' : 'Armenia'},
{'ccode' : 'AW', 'cname' : 'Aruba'},
{'ccode' : 'AU', 'cname' : 'Australia'},
{'ccode' : 'AT', 'cname' : 'Austria'},
{'ccode' : 'AZ', 'cname' : 'Azerbaijan'},
{'ccode' : 'BS', 'cname' : 'Bahamas'},
{'ccode' : 'BH', 'cname' : 'Bahrain'},
{'ccode' : 'BD', 'cname' : 'Bangladesh'},
{'ccode' : 'BB', 'cname' : 'Barbados'},
{'ccode' : 'BY', 'cname' : 'Belarus'},
{'ccode' : 'BE', 'cname' : 'Belgium'},
{'ccode' : 'BZ', 'cname' : 'Belize'},
{'ccode' : 'BJ', 'cname' : 'Benin'},
{'ccode' : 'BM', 'cname' : 'Bermuda'},
{'ccode' : 'BT', 'cname' : 'Bhutan'},
{'ccode' : 'BO', 'cname' : 'Bolivia'},
{'ccode' : 'BA', 'cname' : 'Bosnia And Herzegovina'},
{'ccode' : 'BW', 'cname' : 'Botswana'},
{'ccode' : 'BV', 'cname' : 'Bouvet Island'},
{'ccode' : 'BR', 'cname' : 'Brazil'},
{'ccode' : 'IO', 'cname' : 'British Indian Ocean Territory'},
{'ccode' : 'BN', 'cname' : 'Brunei Darussalam'},
{'ccode' : 'BG', 'cname' : 'Bulgaria'},
{'ccode' : 'BF', 'cname' : 'Burkina Faso'},
{'ccode' : 'BI', 'cname' : 'Burundi'},
{'ccode' : 'KH', 'cname' : 'Cambodia'},
{'ccode' : 'CM', 'cname' : 'Cameroon'},
{'ccode' : 'CA', 'cname' : 'Canada'},
{'ccode' : 'CV', 'cname' : 'Cape Verde'},
{'ccode' : 'KY', 'cname' : 'Cayman Islands'},
{'ccode' : 'CF', 'cname' : 'Central African Republic'},
{'ccode' : 'TD', 'cname' : 'Chad'},
{'ccode' : 'CL', 'cname' : 'Chile'},
{'ccode' : 'CN', 'cname' : 'China'},
{'ccode' : 'CX', 'cname' : 'Christmas Island'},
{'ccode' : 'CC', 'cname' : 'Cocos (Keeling) Islands'},
{'ccode' : 'CO', 'cname' : 'Colombia'},
{'ccode' : 'KM', 'cname' : 'Comoros'},
{'ccode' : 'CG', 'cname' : 'Congo'},
{'ccode' : 'CD', 'cname' : 'Congo, Democratic Republic'},
{'ccode' : 'CK', 'cname' : 'Cook Islands'},
{'ccode' : 'CR', 'cname' : 'Costa Rica'},
{'ccode' : 'HR', 'cname' : 'Croatia'},
{'ccode' : 'CU', 'cname' : 'Cuba'},
{'ccode' : 'CY', 'cname' : 'Cyprus'},
{'ccode' : 'CZ', 'cname' : 'Czech Republic'},
{'ccode' : 'DK', 'cname' : 'Denmark'},
{'ccode' : 'DJ', 'cname' : 'Djibouti'},
{'ccode' : 'DM', 'cname' : 'Dominica'},
{'ccode' : 'DO', 'cname' : 'Dominican Republic'},
{'ccode' : 'EC', 'cname' : 'Ecuador'},
{'ccode' : 'EG', 'cname' : 'Egypt'},
{'ccode' : 'SV', 'cname' : 'El Salvador'},
{'ccode' : 'GQ', 'cname' : 'Equatorial Guinea'},
{'ccode' : 'ER', 'cname' : 'Eritrea'},
{'ccode' : 'EE', 'cname' : 'Estonia'},
{'ccode' : 'ET', 'cname' : 'Ethiopia'},
{'ccode' : 'FK', 'cname' : 'Falkland Islands (Malvinas)'},
{'ccode' : 'FO', 'cname' : 'Faroe Islands'},
{'ccode' : 'FJ', 'cname' : 'Fiji'},
{'ccode' : 'FI', 'cname' : 'Finland'},
{'ccode' : 'FR', 'cname' : 'France'},
{'ccode' : 'GF', 'cname' : 'French Guiana'},
{'ccode' : 'PF', 'cname' : 'French Polynesia'},
{'ccode' : 'TF', 'cname' : 'French Southern Territories'},
{'ccode' : 'GA', 'cname' : 'Gabon'},
{'ccode' : 'GM', 'cname' : 'Gambia'},
{'ccode' : 'GE', 'cname' : 'Georgia'},
{'ccode' : 'DE', 'cname' : 'Germany'},
{'ccode' : 'GH', 'cname' : 'Ghana'},
{'ccode' : 'GI', 'cname' : 'Gibraltar'},
{'ccode' : 'GR', 'cname' : 'Greece'},
{'ccode' : 'GL', 'cname' : 'Greenland'},
{'ccode' : 'GD', 'cname' : 'Grenada'},
{'ccode' : 'GP', 'cname' : 'Guadeloupe'},
{'ccode' : 'GU', 'cname' : 'Guam'},
{'ccode' : 'GT', 'cname' : 'Guatemala'},
{'ccode' : 'GG', 'cname' : 'Guernsey'},
{'ccode' : 'GN', 'cname' : 'Guinea'},
{'ccode' : 'GW', 'cname' : 'Guinea-Bissau'},
{'ccode' : 'GY', 'cname' : 'Guyana'},
{'ccode' : 'HT', 'cname' : 'Haiti'},
{'ccode' : 'HM', 'cname' : 'Heard Island & Mcdonald Islands'},
{'ccode' : 'VA', 'cname' : 'Holy See (Vatican City State)'},
{'ccode' : 'HN', 'cname' : 'Honduras'},
{'ccode' : 'HK', 'cname' : 'Hong Kong'},
{'ccode' : 'HU', 'cname' : 'Hungary'},
{'ccode' : 'IS', 'cname' : 'Iceland'},
{'ccode' : 'IN', 'cname' : 'India'},
{'ccode' : 'ID', 'cname' : 'Indonesia'},
{'ccode' : 'IR', 'cname' : 'Iran, Islamic Republic Of'},
{'ccode' : 'IQ', 'cname' : 'Iraq'},
{'ccode' : 'IE', 'cname' : 'Ireland'},
{'ccode' : 'IM', 'cname' : 'Isle Of Man'},
{'ccode' : 'IL', 'cname' : 'Israel'},
{'ccode' : 'IT', 'cname' : 'Italy'},
{'ccode' : 'JM', 'cname' : 'Jamaica'},
{'ccode' : 'JP', 'cname' : 'Japan'},
{'ccode' : 'JE', 'cname' : 'Jersey'},
{'ccode' : 'JO', 'cname' : 'Jordan'},
{'ccode' : 'KZ', 'cname' : 'Kazakhstan'},
{'ccode' : 'KE', 'cname' : 'Kenya'},
{'ccode' : 'KI', 'cname' : 'Kiribati'},
{'ccode' : 'KR', 'cname' : 'Korea'},
{'ccode' : 'KW', 'cname' : 'Kuwait'},
{'ccode' : 'KG', 'cname' : 'Kyrgyzstan'},
{'ccode' : 'LV', 'cname' : 'Latvia'},
{'ccode' : 'LB', 'cname' : 'Lebanon'},
{'ccode' : 'LS', 'cname' : 'Lesotho'},
{'ccode' : 'LR', 'cname' : 'Liberia'},
{'ccode' : 'LY', 'cname' : 'Libyan Arab Jamahiriya'},
{'ccode' : 'LI', 'cname' : 'Liechtenstein'},
{'ccode' : 'LT', 'cname' : 'Lithuania'},
{'ccode' : 'LU', 'cname' : 'Luxembourg'},
{'ccode' : 'MO', 'cname' : 'Macao'},
{'ccode' : 'MK', 'cname' : 'Macedonia'},
{'ccode' : 'MG', 'cname' : 'Madagascar'},
{'ccode' : 'MW', 'cname' : 'Malawi'},
{'ccode' : 'MY', 'cname' : 'Malaysia'},
{'ccode' : 'MV', 'cname' : 'Maldives'},
{'ccode' : 'ML', 'cname' : 'Mali'},
{'ccode' : 'MT', 'cname' : 'Malta'},
{'ccode' : 'MH', 'cname' : 'Marshall Islands'},
{'ccode' : 'MQ', 'cname' : 'Martinique'},
{'ccode' : 'MR', 'cname' : 'Mauritania'},
{'ccode' : 'MU', 'cname' : 'Mauritius'},
{'ccode' : 'YT', 'cname' : 'Mayotte'},
{'ccode' : 'MX', 'cname' : 'Mexico'},
{'ccode' : 'FM', 'cname' : 'Micronesia, Federated States Of'},
{'ccode' : 'MD', 'cname' : 'Moldova'},
{'ccode' : 'MC', 'cname' : 'Monaco'},
{'ccode' : 'MN', 'cname' : 'Mongolia'},
{'ccode' : 'ME', 'cname' : 'Montenegro'},
{'ccode' : 'MS', 'cname' : 'Montserrat'},
{'ccode' : 'MA', 'cname' : 'Morocco'},
{'ccode' : 'MZ', 'cname' : 'Mozambique'},
{'ccode' : 'MM', 'cname' : 'Myanmar'},
{'ccode' : 'NA', 'cname' : 'Namibia'},
{'ccode' : 'NR', 'cname' : 'Nauru'},
{'ccode' : 'NP', 'cname' : 'Nepal'},
{'ccode' : 'NL', 'cname' : 'Netherlands'},
{'ccode' : 'AN', 'cname' : 'Netherlands Antilles'},
{'ccode' : 'NC', 'cname' : 'New Caledonia'},
{'ccode' : 'NZ', 'cname' : 'New Zealand'},
{'ccode' : 'NI', 'cname' : 'Nicaragua'},
{'ccode' : 'NE', 'cname' : 'Niger'},
{'ccode' : 'NG', 'cname' : 'Nigeria'},
{'ccode' : 'NU', 'cname' : 'Niue'},
{'ccode' : 'NF', 'cname' : 'Norfolk Island'},
{'ccode' : 'MP', 'cname' : 'Northern Mariana Islands'},
{'ccode' : 'NO', 'cname' : 'Norway'},
{'ccode' : 'OM', 'cname' : 'Oman'},
{'ccode' : 'PK', 'cname' : 'Pakistan'},
{'ccode' : 'PW', 'cname' : 'Palau'},
{'ccode' : 'PS', 'cname' : 'Palestinian Territory, Occupied'},
{'ccode' : 'PA', 'cname' : 'Panama'},
{'ccode' : 'PG', 'cname' : 'Papua New Guinea'},
{'ccode' : 'PY', 'cname' : 'Paraguay'},
{'ccode' : 'PE', 'cname' : 'Peru'},
{'ccode' : 'PH', 'cname' : 'Philippines'},
{'ccode' : 'PN', 'cname' : 'Pitcairn'},
{'ccode' : 'PL', 'cname' : 'Poland'},
{'ccode' : 'PT', 'cname' : 'Portugal'},
{'ccode' : 'PR', 'cname' : 'Puerto Rico'},
{'ccode' : 'QA', 'cname' : 'Qatar'},
{'ccode' : 'RE', 'cname' : 'Reunion'},
{'ccode' : 'RO', 'cname' : 'Romania'},
{'ccode' : 'RU', 'cname' : 'Russian Federation'},
{'ccode' : 'RW', 'cname' : 'Rwanda'},
{'ccode' : 'BL', 'cname' : 'Saint Barthelemy'},
{'ccode' : 'SH', 'cname' : 'Saint Helena'},
{'ccode' : 'KN', 'cname' : 'Saint Kitts And Nevis'},
{'ccode' : 'LC', 'cname' : 'Saint Lucia'},
{'ccode' : 'MF', 'cname' : 'Saint Martin'},
{'ccode' : 'PM', 'cname' : 'Saint Pierre And Miquelon'},
{'ccode' : 'VC', 'cname' : 'Saint Vincent And Grenadines'},
{'ccode' : 'WS', 'cname' : 'Samoa'},
{'ccode' : 'SM', 'cname' : 'San Marino'},
{'ccode' : 'ST', 'cname' : 'Sao Tome And Principe'},
{'ccode' : 'SA', 'cname' : 'Saudi Arabia'},
{'ccode' : 'SN', 'cname' : 'Senegal'},
{'ccode' : 'RS', 'cname' : 'Serbia'},
{'ccode' : 'SC', 'cname' : 'Seychelles'},
{'ccode' : 'SL', 'cname' : 'Sierra Leone'},
{'ccode' : 'SG', 'cname' : 'Singapore'},
{'ccode' : 'SK', 'cname' : 'Slovakia'},
{'ccode' : 'SI', 'cname' : 'Slovenia'},
{'ccode' : 'SB', 'cname' : 'Solomon Islands'},
{'ccode' : 'SO', 'cname' : 'Somalia'},
{'ccode' : 'ZA', 'cname' : 'South Africa'},
{'ccode' : 'GS', 'cname' : 'South Georgia And Sandwich Isl.'},
{'ccode' : 'ES', 'cname' : 'Spain'},
{'ccode' : 'LK', 'cname' : 'Sri Lanka'},
{'ccode' : 'SD', 'cname' : 'Sudan'},
{'ccode' : 'SR', 'cname' : 'Suriname'},
{'ccode' : 'SJ', 'cname' : 'Svalbard And Jan Mayen'},
{'ccode' : 'SZ', 'cname' : 'Swaziland'},
{'ccode' : 'SE', 'cname' : 'Sweden'},
{'ccode' : 'CH', 'cname' : 'Switzerland'},
{'ccode' : 'SY', 'cname' : 'Syrian Arab Republic'},
{'ccode' : 'TW', 'cname' : 'Taiwan'},
{'ccode' : 'TJ', 'cname' : 'Tajikistan'},
{'ccode' : 'TZ', 'cname' : 'Tanzania'},
{'ccode' : 'TH', 'cname' : 'Thailand'},
{'ccode' : 'TL', 'cname' : 'Timor-Leste'},
{'ccode' : 'TG', 'cname' : 'Togo'},
{'ccode' : 'TK', 'cname' : 'Tokelau'},
{'ccode' : 'TO', 'cname' : 'Tonga'},
{'ccode' : 'TT', 'cname' : 'Trinidad And Tobago'},
{'ccode' : 'TN', 'cname' : 'Tunisia'},
{'ccode' : 'TR', 'cname' : 'Turkey'},
{'ccode' : 'TM', 'cname' : 'Turkmenistan'},
{'ccode' : 'TC', 'cname' : 'Turks And Caicos Islands'},
{'ccode' : 'TV', 'cname' : 'Tuvalu'},
{'ccode' : 'UG', 'cname' : 'Uganda'},
{'ccode' : 'UA', 'cname' : 'Ukraine'},
{'ccode' : 'AE', 'cname' : 'United Arab Emirates'},
{'ccode' : 'GB', 'cname' : 'United Kingdom'},
{'ccode' : 'US', 'cname' : 'United States'},
{'ccode' : 'UM', 'cname' : 'United States Outlying Islands'},
{'ccode' : 'UY', 'cname' : 'Uruguay'},
{'ccode' : 'UZ', 'cname' : 'Uzbekistan'},
{'ccode' : 'VU', 'cname' : 'Vanuatu'},
{'ccode' : 'VE', 'cname' : 'Venezuela'},
{'ccode' : 'VN', 'cname' : 'Viet Nam'},
{'ccode' : 'VG', 'cname' : 'Virgin Islands, British'},
{'ccode' : 'VI', 'cname' : 'Virgin Islands, U.S.'},
{'ccode' : 'WF', 'cname' : 'Wallis And Futuna'},
{'ccode' : 'EH', 'cname' : 'Western Sahara'},
{'ccode' : 'YE', 'cname' : 'Yemen'},
{'ccode' : 'ZM', 'cname' : 'Zambia'},
{'ccode' : 'ZW', 'cname' : 'Zimbabwe'}
];

return function (countryName) {
  for(var prop in isoCountries1){
      if(isoCountries1.hasOwnProperty(prop)){
          if(isoCountries1[prop]['cname'] === countryName) {
              return isoCountries1[prop]['ccode'];
              break;
          }
      }
  }
}
})






.factory('country_helper',['$http',function($http){
    // var local_host="http://127.0.0.1:8000/";
    var local_host="http://51.145.25.169:8001/";
    var getData = function() {
        // Angular $http() and then() both return promises themselves 
        return $http({method:"GET", url:local_host+"country_list/"}).then(function(result){
            return result.data;
        });
    };
    
    return { getData: getData };   

}]);




